apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files:
      - "alert-rules.yml"

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

      - job_name: 'calorie-api'
        static_configs:
          - targets: ['calorie-api.default.svc.cluster.local:5000']

  alert-rules.yml: |
    groups:
    - name: pod-alerts
      rules:
      - alert: PodDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod is down or unreachable"

      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 0.7
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container CPU usage is high"

