apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calorie-app
  template:
    metadata:
      labels:
        app: calorie-app
    spec:
      containers:
      - name: calorie-app
        image: dharmateja12/calorie-app:latest
        ports:
        - containerPort: 5000
