apiVersion: apps/v1
kind: Deployment
metadata:
  name: calorie-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calorie-api
  template:
    metadata:
      labels:
        app: calorie-api
    spec:
      containers:
      - name: calorie-api
        image: dharmateja12/calorie-api:latest
        ports:
        - containerPort: 5000
