name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubectl for EKS
      run: |
        aws eks update-kubeconfig --name assessment-cluster --region ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t dharmateja12/calorie-api:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker push dharmateja12/calorie-api:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f K8s-manifests/

    - name: Verify Deployment Rollout
      run: |
        kubectl get pods
        kubectl get svc
        kubectl rollout status deployment/calorie-api --namespace=default

    - name: Wait for Prometheus to be Ready
      run: |
        kubectl rollout status deployment/prometheus -n monitoring
    
    - name: Port forward Prometheus
      run: |
        kubectl port-forward svc/prometheus 9090:9090 -n monitoring &
        sleep 10
    
    - name: Confirm Prometheus targets are UP
      run: |
        echo "Checking if Prometheus has any targets UP..."
        curl -s http://localhost:9090/api/v1/targets | grep '"health":"up"' && echo "Prometheus is collecting metrics." || (echo "Prometheus has no healthy targets!" && exit 1)
